disabled_rules:
  - trailing_whitespace
  - multiple_closures_with_trailing_closure
  - missing_docs
  - unneeded_override
  - cyclomatic_complexity
opt_in_rules:
  - empty_count
  - missing_docs
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_parameters_brackets
  - multiline_literal_brackets
  - multiline_function_chains
analyzer_rules:
  - unused_import
  - capture_variable
  - unused_declaration
included:
  - DesignSystemBookApp
excluded:
  - Carthage
  - Pods
  - Source/ExcludedFolder
  - Source/ExcludedFile.swift
force_cast: warning
force_try:
  severity: warning
line_length: 110
type_body_length:
  - 400
  - 500
file_length:
  warning: 500
  error: 800
type_name:
  min_length: 4
  max_length:
    warning: 40
    error: 50
  excluded: iPhone
  allowed_symbols: "_"
identifier_name:
  min_length:
    warning: 3
    error: 2
  excluded:
    - x
    - y
    - id
    - uid
    - URL
    - GlobalAPIKey
  allowed_symbols: "_"
reporter: "xcode"
