disabled_rules:
  - trailing_whitespace
  - multiple_closures_with_trailing_closure
  - missing_docs
opt_in_rules:
  - empty_count
  - missing_docs
analyzer_rules:
  - unused_import
  - capture_variable
  - unused_declaration
included:
  - DesignSystemBookApp
excluded:
  - Carthage
  - Pods
  - Source/ExcludedFolder
  - Source/ExcludedFile.swift
force_cast: warning
force_try:
  severity: warning
line_length: 110
type_body_length:
  - 200
  - 300
file_length:
  warning: 250
  error: 500
type_name:
  min_length: 4
  max_length:
    warning: 40
    error: 50
  excluded: iPhone
  allowed_symbols: "_"
identifier_name:
  min_length:
    warning: 3
    error: 2
  excluded:
    - x
    - y
    - id
    - uid
    - URL
    - GlobalAPIKey
  allowed_symbols: "_"
custom_rules:
  prohibit_lower_snake_case:
    name: "Prohibit Lower Snake Case"
    regex: "[a-z]+_[a-z]+"
    message: "Identifiers should not be written in lower snake case."
    severity: error
reporter: "xcode"
